config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  scope '(:locale)' do
    resources :users

    resources :orders

    resources :line_items

    resources :carts

    get 'store/index'

    resources :products do
      get :who_bought, :on => :member
    end

    root :to => 'store#index' , :as => 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Depot</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>

	<body id="store">
		<div id="banner">
			<!--
			<%= form_tag store_path, :class => 'locale' do %>
			<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s)%>
			<%= submit_tag 'submit' %>			
			<%= javascript_tag "$$('.locale input').each(Element.hide)" %>
			<% end %>
			-->
			<%= image_tag("logo.png" ) %>
			<%= @page_title || t('.title') %>
		</div>
		<div id="columns">
			<div id="side">
				<% if session[:user_id].nil?%>
				<%= link_to 'Login', login_path%>
				<% end %>
				<br/>
				<br/>

				<a href="http://www...."><%= t('.home') %></a>
				<br />
				<a href="http://www..../faq"><%= t('.questions') %></a>
				<br />
				<a href="http://www..../news"><%= t('.news')%></a>
				<br />
				<a href="http://www..../contact"><%= t('.contact')%></a>
				<br/>
				<br/>

				<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path%>
				<br />
				<%= link_to 'Products', products_path %>
				<br />
				<%= link_to 'Users', users_path%>
				<br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				<br/>
				<br/>

				<% if @cart %>

				<div id="cart">
					<%= render @cart %>
				</div>

				<% end %>
			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
</html>